import { Analyzer } from "../components/analyzer";
import { CampaignList } from "../components/campaign-list";
import { trustedBankBrands } from "@lorica/detection";
import { scamCampaigns, threatIntelReport, threatSnapshot } from "@lorica/knowledge";

export function HomePage() {
  return <><section className="hero shell"><p className="eyebrow">Prevención de fraude para España</p><h1>Comprueba antes<br />de <span>actuar.</span></h1><p className="hero-subtitle">Pega un SMS, correo o URL sospechosa. Lorica busca señales de suplantación, presión y manipulación sin abrir el enlace ni enviar el contenido fuera de tu dispositivo.</p><div className="trust-row" aria-label="Garantías del análisis anónimo"><span>Sin registro</span><span>Sin subir el mensaje</span><span>Resultado explicable</span></div></section><Analyzer /><section className="feature-strip shell" aria-label="Características"><article className="feature-card"><span className="feature-icon" aria-hidden="true">Aa</span><h3>Detecta letras engañosas</h3><p>Compara alfabetos, punycode, caracteres invisibles y dominios parecidos a marcas conocidas.</p></article><article className="feature-card"><span className="feature-icon" aria-hidden="true">017</span><h3>Contexto de España</h3><p>Reglas basadas en campañas documentadas por INCIBE: DGT, AEAT, bancos, paquetes y falso familiar.</p></article><article className="feature-card"><span className="feature-icon" aria-hidden="true">◎</span><h3>No navega al destino</h3><p>El MVP analiza la estructura y el texto localmente; no contacta con la web que estás comprobando.</p></article></section></>;
}

export function ThreatsPage() {
  const years = new Set(scamCampaigns.map((item) => item.publishedAt.slice(0, 4))).size;
  const syncedAt = threatSnapshot.generatedAt ? new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Madrid" }).format(new Date(threatSnapshot.generatedAt)) : "nunca";
  const feedErrors = threatIntelReport.status !== "synced-active-feed";
  const failedFeeds = Object.entries(threatIntelReport.feeds).filter(([, feed]) => feed.status !== "ok").map(([name]) => name);
  return <div className="shell"><section className="page-hero"><p className="eyebrow">Inteligencia con fuentes</p><h1>Lo que está pasando en España.</h1><p>Registro de casos documentados por INCIBE, Guardia Civil y Policía Nacional entre noviembre de 2023 y mayo de 2026. No convierte una denuncia aislada en una acusación y conserva el enlace a su fuente.</p></section><section className="stats-grid" aria-label="Resumen del registro"><div className="stat"><strong>{scamCampaigns.length}</strong><span>casos documentados con fuente</span></div><div className="stat"><strong>{years}</strong><span>años con cobertura</span></div><div className="stat"><strong>{threatSnapshot.domains.length.toLocaleString("es-ES")}</strong><span>dominios activos relacionados con España</span></div><div className="stat"><strong>{threatSnapshot.urls.length.toLocaleString("es-ES")}</strong><span>rutas URL activas relacionadas con España</span></div></section><div className={`callout ${feedErrors ? "warning-callout" : ""}`} style={{ marginBottom: 24 }}>Estado: {threatIntelReport.status}; última instantánea: {syncedAt}. Último intento: {new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Madrid" }).format(new Date(threatIntelReport.lastAttemptAt))}. {failedFeeds.length ? `Feeds con fallo: ${failedFeeds.join(", ")}.` : "Ambos feeds se actualizaron."} Indicadores de una fuente comunitaria MIT, filtrados por señales españolas; query strings se eliminan para no republicar tokens/datos personales. El filtro no confirma origen ni culpabilidad. Los teléfonos no se califican sin una fuente pública fiable.</div><CampaignList /></div>;
}

export function MethodologyPage() {
  return <div className="shell"><section className="page-hero"><p className="eyebrow">Explicable por diseño</p><h1>Señales, no veredictos opacos.</h1><p>Cada punto de riesgo corresponde a una regla visible. El MVP nunca abre la URL ni afirma que una persona o empresa sea culpable.</p></section><div className="method-grid"><aside className="method-nav"><strong>En esta página</strong><a href="#url">Estructura de URL</a><a href="#unicode">Tipografías y Unicode</a><a href="#mensaje">Ingeniería social</a><a href="#reputacion">Reputación conocida</a><a href="#dominios-bancarios">Dominios bancarios</a><a href="#scoring">Puntuación</a><a href="#limites">Límites</a><a href="#fuentes">Fuentes técnicas</a></aside><div className="method-content">
    <section id="url"><h2>1. Estructura de la URL</h2><p>El analizador separa protocolo, autoridad, dominio, puerto y ruta. Busca IPs directas, acortadores, HTTP, puertos extraños, demasiados subdominios, rutas de credenciales y el engaño con <code>@</code>.</p><div className="code-example">hxxps://correos[.]es@entrega-segura[.]example/pago<br />Dominio real: entrega-segura[.]example</div><h3>Marca dentro de otro dominio</h3><p>En <code>correos.es.entrega.example</code>, la marca aparece a la izquierda, pero el dominio controlado es <code>entrega.example</code>. Lorica compara contra una lista reducida de dominios oficiales y advierte de parecidos.</p></section>
    <section id="unicode"><h2>2. Tipografías, homógrafos y Unicode</h2><p>Algunos caracteres cirílicos o griegos se parecen a letras latinas. La “o” cirílica de <code>cоrreos</code> puede verse idéntica a una “o” latina. También se comprueban punycode, mezclas de alfabetos y caracteres invisibles o bidireccionales.</p><div className="code-example">correos → letras latinas<br />cоrreos → contiene U+043E CYRILLIC SMALL LETTER O</div><div className="callout">La comparación es una heurística inspirada en Unicode UTS #39, no una implementación completa. La forma cambia según la fuente y puede haber falsos positivos o negativos.</div></section>
    <section id="mensaje"><h2>3. Ingeniería social</h2><p>Las reglas buscan urgencia, amenazas, secreto, credenciales, OTP, pagos irreversibles, control remoto, falsas inversiones, familiar con número nuevo, callback y petición de DNI o nómina.</p><p>Una señal aislada no basta para declarar riesgo crítico: la compuerta exige varias familias fuertes o una coincidencia de reputación conocida.</p></section>
    <section id="reputacion"><h2>4. Registro de dominios y rutas URL conocidas</h2><p>El workflow diario incorpora indicadores activos de <a href="https://github.com/Phishing-Database/Phishing.Database" target="_blank" rel="noreferrer">Phishing.Database</a>, con licencia MIT. Solo descarga texto: no visita los dominios listados. La comparación usa host y ruta exactos; parámetros y fragmentos se ignoran para no republicar tokens o datos personales, por lo que una coincidencia de ruta no prueba que cada variante sea maliciosa.</p><p>El filtro conserva dominios <code>.es</code> o con tokens relacionados con servicios españoles; es una relevancia heurística, no una atribución geográfica. El estado de cada feed y la fecha de actualización aparecen en Inteligencia.</p><p>Los teléfonos no se marcan por listas anónimas: caller ID puede suplantarse y los números se reasignan. Se detectan ciertos prefijos de tarificación especial solo como aviso de coste. Para alias SMS, Lorica enlaza a la <a href="https://numeracionyoperadores.cnmc.es/alias" target="_blank" rel="noreferrer">consulta oficial de la CNMC</a>; la integración de descarga masiva requiere acceso registrado.</p></section>
    <section id="dominios-bancarios"><h2>5. Dominios bancarios oficiales de referencia</h2><p>La lista local sirve para detectar si un mensaje que nombra al banco enlaza fuera de los dominios de referencia reconocidos:</p><ul>{trustedBankBrands.map((brand) => <li key={brand.name}><strong>{brand.name}:</strong> {brand.officialDomains.map((domain, index) => <span key={domain}>{index ? ", " : ""}<code>{domain}</code></span>)}</li>)}</ul><div className="callout warning-callout">“Dominio oficial” no equivale a “enlace garantizado como seguro”: una página legítima puede alojar servicios de terceros y la lista puede quedar incompleta o cambiar. Para operar, abre la aplicación del banco o escribe tú mismo su dirección oficial; no uses el enlace del SMS.</div></section>
    <section id="scoring"><h2>6. Puntuación explicable</h2><p>Las reglas aportan pesos visibles y la suma queda limitada a 100. Las bandas iniciales son 0–24 bajo, 25–49 medio, 50–74 alto y 75–100 crítico con compuerta adicional. Aún no están calibradas estadísticamente.</p></section>
    <section id="limites"><h2>7. Límites</h2><ul><li>No garantiza que un mensaje sea seguro.</li><li>No abre enlaces, descarga archivos, resuelve DNS ni consulta WHOIS en modo anónimo.</li><li>No sustituye un antivirus, el banco, INCIBE o una denuncia.</li><li>No envía el texto a IA o proveedores externos.</li></ul></section>
    <section id="fuentes"><h2>8. Fuentes técnicas</h2><ul><li><a href="https://www.unicode.org/reports/tr39/" target="_blank" rel="noreferrer">Unicode UTS #39</a></li><li><a href="https://www.incibe.es/ciudadania/tematicas/ingenieria-social-fraudes-online/smishing" target="_blank" rel="noreferrer">INCIBE — smishing</a></li><li><a href="https://attack.mitre.org/techniques/T1566/002/" target="_blank" rel="noreferrer">MITRE ATT&amp;CK T1566.002</a></li><li><a href="https://urlhaus.abuse.ch/api/" target="_blank" rel="noreferrer">URLhaus Community API</a></li><li><a href="https://developers.google.com/safe-browsing/reference/rest" target="_blank" rel="noreferrer">Google Safe Browsing API</a>, pendiente de revisión de licencia y privacidad</li></ul></section>
  </div></div></div>;
}

export function AccountPage() {
  const apiUrl = (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/$/u, "") ?? "";
  const authEnabled = Boolean(apiUrl);
  return <div className="shell"><section className="page-hero"><p className="eyebrow">La cuenta es opcional</p><h1>Primero utilidad.<br />Después, identidad.</h1><p>El analizador básico siempre funciona sin iniciar sesión. Una cuenta permite guardar verificaciones privadas, organizar una familia y pedir una segunda opinión.</p></section><div className="account-layout"><section className="account-card"><h2>Acceso con un proveedor de confianza</h2><p>Lorica inicia OAuth en un backend separado. Los secretos de Google y Apple nunca se incluyen en el JavaScript público ni en GitHub Pages.</p><div className="auth-buttons"><a className={`auth-button ${authEnabled ? "" : "disabled"}`} href={authEnabled ? `${apiUrl}/v1/auth/google/start` : "#cuenta"} aria-disabled={!authEnabled}><strong aria-hidden="true">G</strong> Continuar con Google</a><a className={`auth-button apple ${authEnabled ? "" : "disabled"}`} href={authEnabled ? `${apiUrl}/v1/auth/apple/start` : "#cuenta"} aria-disabled={!authEnabled}><strong aria-hidden="true">●</strong> Continuar con Apple</a></div>{!authEnabled ? <div className="status-banner">El despliegue estático público no tiene backend OAuth configurado. El análisis anónimo sigue plenamente disponible.</div> : null}</section><aside className="account-card"><h2>Funciones de la cuenta completa</h2><ul className="capability-list"><li>Historial privado de verificaciones y decisiones.</li><li>Grupo familiar con roles y aislamiento por espacio.</li><li>Solicitud de aprobación mediante un snapshot mínimo.</li><li>Reporte voluntario con consentimiento separado.</li><li>Expediente y exportación de evidencias sanitizadas.</li></ul></aside></div></div>;
}
