import { Analyzer } from "../components/analyzer";
import { CampaignList } from "../components/campaign-list";
import { scamCampaigns, threatSnapshot } from "@lorica/knowledge";

export function HomePage() {
  return <><section className="hero shell"><p className="eyebrow">Prevención de fraude para España</p><h1>Comprueba antes<br />de <span>actuar.</span></h1><p className="hero-subtitle">Pega un SMS, correo o URL sospechosa. Lorica busca señales de suplantación, presión y manipulación sin abrir el enlace ni enviar el contenido fuera de tu dispositivo.</p><div className="trust-row" aria-label="Garantías del análisis anónimo"><span>Sin registro</span><span>Sin subir el mensaje</span><span>Resultado explicable</span></div></section><Analyzer /><section className="feature-strip shell" aria-label="Características"><article className="feature-card"><span className="feature-icon" aria-hidden="true">Aa</span><h3>Detecta letras engañosas</h3><p>Compara alfabetos, punycode, caracteres invisibles y dominios parecidos a marcas conocidas.</p></article><article className="feature-card"><span className="feature-icon" aria-hidden="true">017</span><h3>Contexto de España</h3><p>Reglas basadas en campañas documentadas por INCIBE: DGT, AEAT, bancos, paquetes y falso familiar.</p></article><article className="feature-card"><span className="feature-icon" aria-hidden="true">◎</span><h3>No navega al destino</h3><p>El MVP analiza la estructura y el texto localmente; no contacta con la web que estás comprobando.</p></article></section></>;
}

export function ThreatsPage() {
  const years = new Set(scamCampaigns.map((item) => item.publishedAt.slice(0, 4))).size;
  return <div className="shell"><section className="page-hero"><p className="eyebrow">Inteligencia con fuentes</p><h1>Lo que está pasando en España.</h1><p>Registro editorial de campañas publicadas por INCIBE dentro de la ventana agosto de 2023–agosto de 2026. No convierte una denuncia aislada en una acusación y siempre conserva la fuente.</p></section><section className="stats-grid" aria-label="Resumen del registro"><div className="stat"><strong>{scamCampaigns.length}</strong><span>campañas oficiales documentadas</span></div><div className="stat"><strong>{years}</strong><span>años con cobertura</span></div><div className="stat"><strong>{threatSnapshot.domains.length.toLocaleString("es-ES")}</strong><span>dominios activos sincronizados</span></div></section>{threatSnapshot.generatedAt === null ? <div className="callout" style={{ marginBottom: 24 }}>La lista automática de dominios todavía no se ha sincronizado. GitHub Actions la actualizará desde la fuente MIT de Phishing.Database; mientras tanto, el motor utiliza análisis heurístico y las campañas verificadas.</div> : null}<CampaignList /></div>;
}

export function MethodologyPage() {
  return <div className="shell"><section className="page-hero"><p className="eyebrow">Explicable por diseño</p><h1>Señales, no veredictos opacos.</h1><p>Cada punto de riesgo corresponde a una regla visible. El MVP nunca abre la URL ni afirma que una persona o empresa sea culpable.</p></section><div className="method-grid"><aside className="method-nav"><strong>En esta página</strong><a href="#url">Estructura de URL</a><a href="#unicode">Tipografías y Unicode</a><a href="#mensaje">Ingeniería social</a><a href="#reputacion">Reputación conocida</a><a href="#scoring">Puntuación</a><a href="#limites">Límites</a><a href="#fuentes">Fuentes técnicas</a></aside><div className="method-content">
    <section id="url"><h2>1. Estructura de la URL</h2><p>El analizador separa protocolo, autoridad, dominio, puerto y ruta. Busca IPs directas, acortadores, HTTP, puertos extraños, demasiados subdominios, rutas de credenciales y el engaño con <code>@</code>.</p><div className="code-example">hxxps://correos[.]es@entrega-segura[.]example/pago<br />Dominio real: entrega-segura[.]example</div><h3>Marca dentro de otro dominio</h3><p>En <code>correos.es.entrega.example</code>, la marca aparece a la izquierda, pero el dominio controlado es <code>entrega.example</code>. Lorica compara contra una lista reducida de dominios oficiales y advierte de parecidos.</p></section>
    <section id="unicode"><h2>2. Tipografías, homógrafos y Unicode</h2><p>Algunos caracteres cirílicos o griegos se parecen a letras latinas. La “o” cirílica de <code>cоrreos</code> puede verse idéntica a una “o” latina. También se comprueban punycode, mezclas de alfabetos y caracteres invisibles o bidireccionales.</p><div className="code-example">correos → letras latinas<br />cоrreos → contiene U+043E CYRILLIC SMALL LETTER O</div><div className="callout">La comparación es una heurística inspirada en Unicode UTS #39, no una implementación completa. La forma cambia según la fuente y puede haber falsos positivos o negativos.</div></section>
    <section id="mensaje"><h2>3. Ingeniería social</h2><p>Las reglas buscan urgencia, amenazas, secreto, credenciales, OTP, pagos irreversibles, control remoto, falsas inversiones, familiar con número nuevo, callback y petición de DNI o nómina.</p><p>Una señal aislada no basta para declarar riesgo crítico: la compuerta exige varias familias fuertes o una coincidencia de reputación conocida.</p></section>
    <section id="reputacion"><h2>4. Registro de dominios conocidos</h2><p>El workflow diario puede incorporar dominios activos de <a href="https://github.com/Phishing-Database/Phishing.Database" target="_blank" rel="noreferrer">Phishing.Database</a>, con licencia MIT. Solo descarga texto: no visita los dominios listados.</p><p>El filtro conserva dominios <code>.es</code> o con tokens relacionados con servicios españoles; es una relevancia heurística, no una atribución geográfica.</p></section>
    <section id="scoring"><h2>5. Puntuación explicable</h2><p>Las reglas aportan pesos visibles y la suma queda limitada a 100. Las bandas iniciales son 0–24 bajo, 25–49 medio, 50–74 alto y 75–100 crítico con compuerta adicional. Aún no están calibradas estadísticamente.</p></section>
    <section id="limites"><h2>6. Límites</h2><ul><li>No garantiza que un mensaje sea seguro.</li><li>No abre enlaces, descarga archivos, resuelve DNS ni consulta WHOIS en modo anónimo.</li><li>No sustituye un antivirus, el banco, INCIBE o una denuncia.</li><li>No envía el texto a IA o proveedores externos.</li></ul></section>
    <section id="fuentes"><h2>7. Fuentes técnicas</h2><ul><li><a href="https://www.unicode.org/reports/tr39/" target="_blank" rel="noreferrer">Unicode UTS #39</a></li><li><a href="https://www.incibe.es/ciudadania/tematicas/ingenieria-social-fraudes-online/smishing" target="_blank" rel="noreferrer">INCIBE — smishing</a></li><li><a href="https://attack.mitre.org/techniques/T1566/002/" target="_blank" rel="noreferrer">MITRE ATT&amp;CK T1566.002</a></li><li><a href="https://urlhaus.abuse.ch/api/" target="_blank" rel="noreferrer">URLhaus Community API</a></li><li><a href="https://developers.google.com/safe-browsing/reference/rest" target="_blank" rel="noreferrer">Google Safe Browsing API</a>, pendiente de revisión de licencia y privacidad</li></ul></section>
  </div></div></div>;
}

export function AccountPage() {
  const apiUrl = (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/$/u, "") ?? "";
  const authEnabled = Boolean(apiUrl);
  return <div className="shell"><section className="page-hero"><p className="eyebrow">La cuenta es opcional</p><h1>Primero utilidad.<br />Después, identidad.</h1><p>El analizador básico siempre funciona sin iniciar sesión. Una cuenta permite guardar verificaciones privadas, organizar una familia y pedir una segunda opinión.</p></section><div className="account-layout"><section className="account-card"><h2>Acceso con un proveedor de confianza</h2><p>Lorica inicia OAuth en un backend separado. Los secretos de Google y Apple nunca se incluyen en el JavaScript público ni en GitHub Pages.</p><div className="auth-buttons"><a className={`auth-button ${authEnabled ? "" : "disabled"}`} href={authEnabled ? `${apiUrl}/v1/auth/google/start` : "#cuenta"} aria-disabled={!authEnabled}><strong aria-hidden="true">G</strong> Continuar con Google</a><a className={`auth-button apple ${authEnabled ? "" : "disabled"}`} href={authEnabled ? `${apiUrl}/v1/auth/apple/start` : "#cuenta"} aria-disabled={!authEnabled}><strong aria-hidden="true">●</strong> Continuar con Apple</a></div>{!authEnabled ? <div className="status-banner">El despliegue estático público no tiene backend OAuth configurado. El análisis anónimo sigue plenamente disponible.</div> : null}</section><aside className="account-card"><h2>Funciones de la cuenta completa</h2><ul className="capability-list"><li>Historial privado de verificaciones y decisiones.</li><li>Grupo familiar con roles y aislamiento por espacio.</li><li>Solicitud de aprobación mediante un snapshot mínimo.</li><li>Reporte voluntario con consentimiento separado.</li><li>Expediente y exportación de evidencias sanitizadas.</li></ul></aside></div></div>;
}
