// Generated by scripts/sync-threat-intel.mjs. Do not edit manually.
export const threatIntelReport = {
  "lastAttemptAt": "2026-10-02T10:45:22.393Z",
  "lastSuccessfulAt": "2026-10-02T10:45:22.393Z",
  "status": "synced-active-feed",
  "feeds": {
    "phishing-domains": {
      "url": "https://raw.githubusercontent.com/Phishing-Database/Phishing.Database/master/phishing-domains-ACTIVE.txt",
      "status": "ok",
      "sourceLines": 392174
    },
    "phishing-urls": {
      "url": "https://raw.githubusercontent.com/Phishing-Database/Phishing.Database/master/phishing-links-ACTIVE.txt",
      "status": "ok",
      "sourceLines": 789055
    }
  },
  "totalRelevantDomains": 2397,
  "totalRelevantUrls": 4668,
  "relevancePolicy": "TLD .es o token asociado a marcas/servicios españoles; no implica atribución geográfica confirmada",
  "errors": []
} as const;
